language: node_js
node_js:
- '10'
- '12'
cache:
  directories:
  - node_modules
after_success:
  - node node_modules/.bin/jest --coverage --config jest-config.json && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
